version: '3.9'

services:
  frontend:
    ports:
      - "8000:8000"
    depends_on:
      - backend
      - ml-service
    volumes:
      - ./frontend:/usr/src/frontend
      - shared-volume:/usr/src/shared-volume
    build: ./frontend

  backend:
    ports:
      - "8001:8001"
    depends_on:
      - ml-service
    volumes:
      - ./backend:/usr/src/backend
      - shared-volume:/usr/src/shared-volume
    build: ./backend

  ml-service:
    ports:
      - "8002:8002"
    volumes:
      - ./ml_service:/usr/src/ml_service
      - shared-volume:/usr/src/shared-volume
    build: ./ml_service

volumes:
  shared-volume: