version: '3.9'

services:
  frontend:
    ports:
      - "8000:8000"
    depends_on:
      - backend
      - mymodel
    volumes:
      - ./frontend:/usr/src/frontend
      - shared-volume:/usr/src/shared-volume
    build: ./frontend

  backend:
    ports:
      - "8001:8001"
    depends_on:
      - mymodel
    volumes:
      - ./backend:/usr/src/backend
      - shared-volume:/usr/src/shared-volume
    build: ./backend

  mymodel:
    ports:
      - "8002:8002"
    volumes:
      - ./mymodel:/usr/src/mymodel
      - shared-volume:/usr/src/shared-volume
    build: ./mymodel
    environment:
      - TF_ENABLE_ONEDNN_OPTS=0

volumes:
  shared-volume: